import { SessionProvider } from 'next-auth/react';
import type { Metadata } from 'next';
import { auth } from '@/lib/auth';
import Header from './components/Headers';
import Footer from './components/Footer';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Hanaro 2024 nextjs project',
  description: 'Generated by insoo',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang='ko'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
